version: '3.8'

services:
  broker:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
    - 3306:3306
    - 33060:33060
    env_file: mariadb.env
    volumes:
    - mariadb_data:/var/lib/mysql
    - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  mariadb_data: