version: '3.8'

services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
    - 1883:1883
    - 9001:9001
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto.passwd:/mosquitto/config/mosquitto.passwd
    - broker_data:/mosquitto/data
    - broker_logs:/mosquitto/log

volumes:
  broker_data:
  broker_logs: